version: 2
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: symlink_creator.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

loggers:
  symlink_creator:
    level: DEBUG
    handlers: [file, console]
    propagate: no

root:
  level: INFO
  handlers: [file, console]

# New configuration options
output_options:
  console_output: true
  file_output: true
  markdown_viewer: true